// This function will map a range of food names generated by the AI output and link to our database of images

export const getImageName = (outputName) => {
	const databaseImages = [
		'avocado',
		'banana',
		'berries',
		'broccoli',
		'carrot',
		'chicken',
		'eggs',
		'hummus',
		'oat',
		'quinoa',
		'salad',
		'salmon',
		'potato',
		'toast',
		'whey',
		'yogurt',
	];
	let imageName = 'undefined';
	for (var i = 0; i < databaseImages.length; i++) {
		if (outputName?.toLowerCase().indexOf(databaseImages[i]) > -1) {
			imageName = databaseImages[i];
			break;
		}
	}
	return imageName;
};
